### ISSUE TITLE
The PlaceholderAPI expansion doesn't work with the latest PlaceholderAPI (2.10.7)

### ISSUE THREAD

**Issue by ChrisTaylor201** [BenCodez/VotingPlugin#888]
#### Versions
Server core – PaperMC 1.15.2 build 384
Plugin – 5.22
PlaceholderAPI expansion – 1.2

#### Describe the bug
Due to the recent changes in [the latest PlaceholderAPI update 2.10.7](https://www.spigotmc.org/resources/placeholderapi.6245/update?update=351340), the PlaceholderAPI expansion won't start; it will result in an exception:
```
[12:23:32] [Server thread/ERROR]: [PlaceholderAPI] expansion class VotingPliuginExpansion is outdated: 
Failed to load due to a [NoSuchMethodError], attempted to use me.clip.placeholderapi.PlaceholderAPI.registerPlaceholderHook(Ljava/lang/String;Lme/clip/placeholderapi/PlaceholderHook;)Z
```

#### How to reproduce
1. Install the latest PlaceholderAPI update (2.10.7).
2. Check the issue mentioned above.

#### Expected behavior
The expansion should start without a problem.

**Comment by BenCodez** [comment]
Just uploaded a new expansion, see if that works

**Comment by ChrisTaylor201** [comment]
The expansion loads without any exceptions now, however the placeholders aren't translated.

**Comment by Momshroom** [comment]
I can confirm.

**Comment by BenCodez** [comment]
Yeah working on it... might be a bit.

**Comment by BenCodez** [comment]
https://ci.extendedclip.com/job/PlaceholderAPI/

Use that with the expansion I just upload to the cloud, should solve your trouble.

**Comment by ChrisTaylor201** [comment]
The latest PlaceholderAPI version (2.10.8) works perfectly with the updated PlaceholderAPI expansion (1.3.1), thank you very much!
