### ISSUE TITLE
Book GUI not working on 1.17

### ISSUE THREAD

**Issue by ThatPerkel** [BenCodez/VotingPlugin#1178]
**Versions**
PaperMC 1.17.1, Build 91
VotingPlugin 6.4.1

**Describe the bug**
Book GUI is not working on 1.17 Paper. When player enters /vote, an Exception is fired (log below).

**Additional context**
Error log:
[11:03:00 WARN]: [VotingPlugin] Plugin VotingPlugin v6.4.1 generated an exception while executing task 10797
java.lang.NoClassDefFoundError: Could not initialize class com.bencodez.votingplugin.upperlevel.book.NmsBookHelper
at com.bencodez.votingplugin.upperlevel.book.BookUtil$BookBuilder.pages(BookUtil.java:147) ~[?:?]
at com.bencodez.votingplugin.advancedcore.api.bookgui.BookWrapper.open(BookWrapper.java:83) ~[?:?]
at com.bencodez.votingplugin.commands.gui.player.VoteURL.onBook(VoteURL.java:153) ~[?:?]
at com.bencodez.votingplugin.advancedcore.api.gui.GUIHandler.open(GUIHandler.java:47) ~[?:?]
at com.bencodez.votingplugin.commands.gui.player.VoteURL.open(VoteURL.java:241) ~[?:?]
at com.bencodez.votingplugin.commands.CommandLoader$114.execute(CommandLoader.java:2213) ~[?:?]
at com.bencodez.votingplugin.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:425) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-91]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-91]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-91]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/
This work?
