### ISSUE TITLE
MonthlyAwards Enchants not working on items.

### ISSUE THREAD

**Issue by TomLewis** [BenCodez/VotingPlugin#948]
**Versions**
Paper 1.12.2
VP: 5.23.3

**Describe the bug**
Ages ago when you updated to add 1.12.2 support I forgot to report this, but when I first moved to the later versions Enchants stopped being added to MonthlyAwards, heres my configs. I couldnt find if you changed the syntrax in your docs.
https://gist.github.com/TomLewis/673dcc6b0a26f18bb48d1f3cb7c675aa

Also is there a command to test the item by spawning it with a command?

**Comment by BenCodez** [comment]
I got no idea. Might be a thing that just won't work in 1.12? Try vanilla names?

**Comment by TomLewis** [comment]
This is not stale, this is still broken.

**Comment by BenCodez** [comment]
You never answered my reply

**Comment by TomLewis** [comment]
Updated to :
```
        DiamondSword:
          Material: 'DIAMOND_SWORD'
          Data: 0
          Amount: 1
          Name: '&0▂▃&8▅▇&7█▓&f▒░ &e&lLIGHTBRINGER &f░▒&7▓█&8▇▅&0▃▂'
          Lore: 
          - '&aAwarded for most monthly Votes'
          - '&2%player%'
          - '&3%date%'
          Enchants:
            unbreaking: 4
            efficiency: 4
            fire_aspect: 2
            sweeping: 3
            looting: 2
```

Did not work, broke it entirely, throwing error:
```
[18:26:07] [Craft Scheduler Thread - 1658/WARN]: [VotingPlugin] Plugin VotingPlugin v5.23.3 generated an exception while executing task 1263646
java.lang.NoSuchMethodError: 'org.bukkit.enchantments.Enchantment org.bukkit.enchantments.Enchantment.getByKey(org.bukkit.NamespacedKey)'
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Item.ItemBuilder.addEnchantments(ItemBuilder.java:308) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Item.ItemBuilder.<init>(ItemBuilder.java:181) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.RewardHandler$94.onRewardRequested(RewardHandler.java:1637) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.Injected.RewardInjectKeys.onRewardRequest(RewardInjectKeys.java:24) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.Injected.RewardInjectKeys.onRewardRequest(RewardInjectKeys.java:12) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.Reward.giveInjectedRewards(Reward.java:209) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.Reward.giveRewardUser(Reward.java:368) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.Reward.giveReward(Reward.java:329) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.RewardHandler.giveReward(RewardHandler.java:383) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Rewards.RewardHandler.giveReward(RewardHandler.java:395) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Commands.CommandLoader$4.execute(CommandLoader.java:134) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.CommandAPI.CommandHandler$1.run(CommandHandler.java:399) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1617]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by BenCodez** [comment]
How's this?
http://bencodez.com/job/VotingPlugin-6.0/
